### PR TITLE
Suppressed the error thrown to the console on every bot restart

### PR DESCRIPTION
**Pull request by DevilXD**
The react_role cog is awesome, but throws an error on every bot restart, about a task being destroyed while it was pending.

This should solve the issue. Not sure if it there should be `break` or `pass` there, feel free to change if I'm wrong ofc.

### CODE REVIEW

**Comment by ZeLarpMaster** [comment]
Did you try your changes?

The "Task was destroyed but it is still pending" error comes from the event loop not having time to cancel all tasks. It's generated by the event loop when it closes. Afaik it is not even an exception. It just prints the message on stdout.

The problem is actually redbot/discord.py not giving time to cleanup tasks when restarting. This is because cancelling tasks occurs on the next event loop (as seen [in the docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.cancel)) instead of instantly. A real fix to this would be redbot/discord.py allowing another tick of the async loop before actually killing the loop.

I doubt I can do anything about that error. I've already tried in the past, and the best I could achieve was the `with contextlib.suppress(RuntimeError)` seen a few lines above.

Anyway, I'll at least try your suggestion to see if it does indeed prevent the error. If it does, I'll make it fit my style to keep the cog consistent.

**Comment by DevilXD** [comment]
Yeah, didn't try the changes, but I'm using this exact solution in at least 2 of my cogs and a try-catch block like that on the async part the loop, that hangs the most time there, and return on that exception, always stopped that error in the console. You could then get rid of that async with contextlib part since it wouldn't be needed I think.

**Comment by DevilXD** [comment]
Actually, I've just been playing with my bot and it started throwing that error again. I tried a different approach, according to [this](https://stackoverflow.com/questions/40897428/please-explain-task-was-destroyed-but-it-is-pending) (at the very bottom):

`
try:
    await asyncio.sleep(600)
except asyncio.CancelledError as e:
    self.save() #Save settings
    raise e # Raise a proper error
`

This seems to prevent it from appearing. Kinda doesn't make sense, but it works ¯\_(ツ)_/¯ Might be worth trying in your case as well.

**Comment by DevilXD** [comment]
Ok, so I checked and you were using a different task scheduling method than me. In that case, just simple `return` was enough to exit the task properly. I also added a task cancel part in the `__unload` section, because it turns out you weren't canceling it at all which made the task stick (and possibly even have multiple copies of it running) between cog reloads - the bot doesn't clean pending tasks automatically.

That also got rid of the RuntimeError, so I removed the `contextlib` wrapper too. Tested it and nothing showed up after 5 restarts, so it should be good now.

**Comment by ZeLarpMaster** [comment]
I agreed with keeping the processing task and cancelling it so I kept it, but I really didn't like the additional try/except especially with a return in the except.
There was already a `contextlib.suppress` for exceptions, the only problem with it is `asyncio.CancelledError` doesn't extend `RuntimeError`, it extends `Exception` instead. So I just added CancelledError to the suppress and now it does what you did *but* it doesn't remove the `self.logger.debug` at the end of the processing task.

I'll close this PR since I pushed it myself.

Side note: you didn't modify react_roles_bundled.

**Pull request closed without merging**
